---
title: "[JS] 프로미스 개념부터 활용까지 요약"
date: "2021-07-25"
template: "post"
draft: false
slug: "[JS]-프로미스-개념부터-활용까지-요약"
category: "JavaScript"  
tags:
  - "#JavaScript"
description: ""
---

이 게시물은 [자바스크립트 12. 프로미스 개념부터 활용까지 JavaScript Promise | 프론트엔드 개발자 입문편 (JavaScript ES6)](https://www.youtube.com/watch?v=JB_yU6Oe2eE)를 요약했습니다.

# promise

비동기 수행을 위해 콜백 대신 사용할 수 있는 오브젝트

## state

1. pending: 연산이 수행 중
2. fulfilled: `pending`에서 성공적으로 끝냈을 때
3. rejected: `pending`에서 파일을 찾지 못하거나 네트워크에 문제가 생겼을 시

## Producer, Consumer

+ Producer: 우리가 원하는 기능을 수행해서 해당하는 데이터를 만들어냄
+ Consumer: 데이터를 소비함

## resolve, reject

![Promise-01.png](/media/posts/2021-07-25---[JS]-프로미스-개념부터-활용까지-요약/Promise-01.png)

`promise`의 생성자를 보면 `executor`라는 콜백 함수를 전달해 줘야되는 데 다시 `executor`를 살펴보면 `resolve`, `reject`를 콜백 함수로 전달합니다.

+ resolve: 기능을 정상적으로 수행해서 마지막에 최종 데이터를 전달함
+ reject: 기능 수행 중 중간에 문제가 생길 시 호출

`Promise`를 생성하는 순간 `executor`가 실행된다.

```JS
// when new Promise is created,
// the executor runs automatically.
const promise = new Promise((resolve, reject)=> {
    // doing some heavy work (network, read files)
    console.log('doing something...')
})
```

### resolve 실습

`producer` 생성

```JS
const promise = new Promise((resolve, reject)=> {
    // doing some heavy work (network, read files)
    console.log('doing something...')
    setTimeout(() => {
        resolve('ellie')
    }, 2000)
})
```

`consumers` 생성

```JS
promise.then((value) => {
    console.log(value) // ellie
})
```

`then`은 `resolve` 콜백함수가 전달한 값이 파라미터로 전달된다.

### reject 실습

`producer` 생성, 네트워크가 문제 생겼다고 가정한다.

```JS
const promise = new Promise((resolve, reject)=> {
    // doing some heavy work (network, read files)
    console.log('doing something...')
    setTimeout(() => {
        reject(new Error('no network'))
    }, 2000)
})
```
```Bash
VM5131:5 Uncaught (in promise) Error: no network
    at <anonymous>:5:16
```

`producer` 생성, `catch` 키워드를 통해 에러를 처리한다.

```JS
promise
.then(value => {
    console.log(value)
})
.catch(error => {
    console.log(error)
})
.finally(() => {
  console.log('finally')
})
```
```Bash
Error: no network
    at <anonymous>:5:16
```
console에 다음같이 출력 된다.  
`then`은 Promiss를 반환하기 때문에 바로 뒤에 `catch`를 사용할 수 있다.  
이것을 `체이닝`이라고 한다.

## chaining

```JS
const fetchNumber = new Promise((resolve, reject) => {
    setTimeout(() => resolve(1), 1000)
})

fetchNumber
.then(num => num*2)
.then(num => num*3)
.then(num => {
    return new Promise((resolve, reject) => {
        setTimeout(() => resolve(num-1), 1000) 
    })
})
.then(num => console.log(num)) // 2초 뒤 5 출력
```

### Error Handling

```JS
const getHen = () =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve('🐓'), 1000)
  })
const getEgg = hen =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${hen} => 🥚`), 1000)
})
const cook = egg =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${egg} => 🍳`), 1000)
})

getHen()
.then(hen1 => getEgg(hen1))
.then(egg => cook(egg))
.then(meal => console.log(meal))

// 🐓 => 🥚 => 🍳
```

여기서 콜백함수를 사용 시 받아오는 값을 바로 다른 함수로 전달 시 다음과 같이 작성할 수 있다.

```JS
getHen()
  .then(getEgg)
  .then(cook)
  .then(console.log)
```

에러가 발생한다면 어떻게 될까?

```JS
const getEgg = hen =>
  new Promise((resolve, reject) => {
    setTimeout(() => reject(new Error(`error! ${hen} => 🥚`)), 1000)
})
```
```Bash
Uncaught (in promise) Error: error! 🐓 => 🥚
    at <anonymous>:7:29
```
제일 아래에 `catch` 키워드를 사용하여 에러를 핸들링 해보자

```JS
getHen()
  .then(getEgg)
  .then(cook)
  .then(console.log)
  .catch(console.log)
```
```Bash
Error: error! 🐓 => 🥚
    at <anonymous>:7:29
```
계란을 얻어오는 데 실패했다면 빵을 얻어서 코드를 처리하도록 수정해보자

```JS
getHen()
  .then(getEgg)
  .catch(error => {
    return '🌭'
  })
  .then(cook)
  .then(console.log)
  .catch(console.log)

  // 🌭 => 🍳
```

##### reference

[자바스크립트 12. 프로미스 개념부터 활용까지 JavaScript Promise | 프론트엔드 개발자 입문편 (JavaScript ES6)](https://www.youtube.com/watch?v=JB_yU6Oe2eE)